name: Continued integration with nodejs

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm run build

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Deploy to test-front-erick01.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "test-front-erick01.surge.sh"
          project: "front"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
