name: Continued integration with nodejs

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar y ubicarse en la rama main
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm test

  # build:
  #   runs-on: ubuntu-latest
  #   needs: [test]
  #   steps:
  #     - name: CLonar y ubicarse en la rama main
  #       uses: actions/checkout@v2
  #     - name: Instalar dependencias
  #       run: npm install
  #     - name: Ejecutar test
  #       run: npm build
  #

  cd-surge:
    runs-on: ubuntu-latest
    working-directory: front
    needs: [test]
    steps:
      - name: Deploy to test-front-erick01.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "test-front-erick01.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v1
      #  with:
      #    node-version: 12
      #- run: npm ci
      #- run: npm test
